"""Stage 2: Verification question formulation."""

import logging

from relcheck_v3.claim_generation.models import (
    AttributeQuestion,
    FormulatedQuestions,
    ObjectQuestion,
)
from relcheck_v3.claim_generation.openai_client import OpenAIClient
from relcheck_v3.claim_generation.prompts import (
    OBJECT_QUESTION_TEMPLATE,
    STAGE2_EXAMPLES,
    STAGE2_SYSTEM_MESSAGE,
    STAGE2_USER_TEMPLATE,
)

logger = logging.getLogger(__name__)


class QuestionFormulator:
    """Generates object-level and attribute-level verification questions.

    Object-level questions are hardcoded (one per concept). Attribute-level
    questions are generated by GPT-5.4-mini using the exact Woodpecker paper
    prompt (Table 5, Appendix A.2).
    """

    def __init__(self, client: OpenAIClient) -> None:
        """Store the OpenAI client instance."""
        self._client = client

    def formulate(self, caption: str, concepts: list[str]) -> FormulatedQuestions:
        """Generate verification questions for the given caption and concepts.

        Produces one hardcoded object-level question per concept, plus
        LLM-generated attribute-level questions about object attributes.

        Args:
            caption: The caption string to formulate questions about.
            concepts: List of key concept strings extracted from the caption.

        Returns:
            FormulatedQuestions with object_questions and attribute_questions.
            Falls back to object questions only if the LLM returns "None"
            or if the API call fails after retries.
        """
        # Object-level: one hardcoded question per concept
        object_questions = [
            ObjectQuestion(
                object_name=concept,
                question=OBJECT_QUESTION_TEMPLATE.format(object=concept),
            )
            for concept in concepts
        ]

        # Attribute-level: LLM-generated questions
        attribute_questions = self._generate_attribute_questions(caption, concepts)

        return FormulatedQuestions(
            object_questions=object_questions,
            attribute_questions=attribute_questions,
        )

    def _generate_attribute_questions(
        self, caption: str, concepts: list[str]
    ) -> list[AttributeQuestion]:
        """Query GPT-5.4-mini for attribute-level verification questions.

        Returns an empty list if the LLM responds with "None" or if the
        API call fails after retries (graceful fallback).
        """
        entities_str = ".".join(concepts)

        user_message = STAGE2_USER_TEMPLATE.format(
            examples=STAGE2_EXAMPLES,
            sentence=caption,
            entities=entities_str,
        )

        try:
            response = self._client.chat(STAGE2_SYSTEM_MESSAGE, user_message)
        except Exception:
            logger.warning(
                "Attribute question generation failed for caption: %.80s. "
                "Falling back to object questions only.",
                caption,
            )
            return []

        response = response.strip()

        if response == "None":
            return []

        return self._parse_attribute_response(response)

    @staticmethod
    def _parse_attribute_response(response: str) -> list[AttributeQuestion]:
        """Parse multi-line LLM response into AttributeQuestion objects.

        Each line has the format: "question text & entity1.entity2"
        Lines without a valid "&" delimiter are skipped.
        """
        questions: list[AttributeQuestion] = []

        for line in response.splitlines():
            line = line.strip()
            if not line:
                continue

            parts = line.split("&", maxsplit=1)
            if len(parts) != 2:
                continue

            question_text = parts[0].strip()
            entities_raw = parts[1].strip()

            if not question_text or not entities_raw:
                continue

            entities = [e.strip() for e in entities_raw.split(".") if e.strip()]
            if not entities:
                continue

            questions.append(
                AttributeQuestion(question=question_text, entities=entities)
            )

        return questions
